### PR TITLE
Add capability for pathlib.Paths

### PR DESCRIPTION
**Pull request by michaelaye**
I'm not sure this is sufficient, but this would be a start to make pvl pathlib.Path compatible.

### CODE REVIEW

**Comment by godber** [comment]
Hi Michael, thanks for the pull request.  I am not sure what you mean, well, I guess I kind of know what pathlib is.  Could you implement a test that this makes pass so I can see it in code?

**Comment by michaelaye** [comment]
sure, but where do you want the test, as this is a change in the `__init__.py` and I don't see an appropriate file for it in `tests/` ?

**Comment by godber** [comment]
It looks like `test_decoder.py` contains `test_cube_label` and `test_pds3_sample_image` which use `pvl.load`.

If I understand your request correctly, your change would address the use of a `pathlib` based path instead of `os.path` like shown on this line:

```
def test_cube_label():
    with open(os.path.join(DATA_DIR, 'pattern.cub'), 'rb') as fp:
        label = pvl.load(fp)
```

https://github.com/planetarypy/pvl/blob/master/tests/test_decoder.py#L647

**Comment by wtolson** [comment]
Hey guys, sorry to jump in late. If we do want to add this, I have a few concerns I'd like to address:

- If we support pathlib paths in `pvl.load`, we should also support them in `pvl.dump`.
- This implementation assumes it will be on a posix system and will break on windows™. We should probably just cast to string after detecting it is not a fileobject.
-  Tests should be in test_encoder.py/test_decoder.py respectively for load/dump.

I'm not against adding this but wanted to also check in with what's the advantage to adding this in pvl as opposed to simply:

    pvl.load(filename.as_posix())

Thanks again @michaelaye

**Comment by michaelaye** [comment]
Totally agree with the consistency and was waiting for somebody knowing this library better than me to suggest where to implement this.
Reason for adding it here is simply convenience during interactive data analysis. I'm getting tired of remembering that pvl does not do pathlib.Paths while pandas and some other libraries already support it (even so Pandas has an open ticket to `really` finish their support on this, as it's half-baked only.

**Comment by wtolson** [comment]
Awesome, it will be good to follow pandas lead in implementation, looks like this would be a good start here: https://github.com/pydata/pandas/blob/6f1ade19601ca947a161e0baa7a8cb3c5687f96a/pandas/io/common.py#L271.

Do you have a link to the issue where they discuss implementation?

**Comment by michaelaye** [comment]
This is it: https://github.com/pydata/pandas/issues/11773

**Comment by michaelaye** [comment]
I like the way with their global variable that is TRUE if pathlib is installed. that way one doesn't create a dependency. Think I should do it in a similar way, right?

**Comment by wtolson** [comment]
I like how they've implemented it as well. I think following their example would be a good idea.

**Comment by AndrewAnnex** [comment]
@michaelaye isn't pathlib part of the standard library? unless for really old python versions (2.7 and older)

**Comment by michaelaye** [comment]
yes? That doesn't mean that a package supports it?

**Comment by AndrewAnnex** [comment]
I'm very confused, if it is part of the standard library then why would there need to be a test for it to be installed? Are there ways to uninstall portions of the standard library? What I mean to say is that pathlib does not add a dependency as it is guaranteed to be included with all python distributions.

**Comment by AndrewAnnex** [comment]
ok pathlib was added as of 3.4, the check makes sense if you want to continue legacy python (2.7,2.6, etc) support

**Comment by michaelaye** [comment]
i'm not sure what test are you talking about, as this ticket is about pvl supporting in general the use of the pathlib package?

**Comment by AndrewAnnex** [comment]
The one you mention a few comments up the on this page?

-Andrew Annex

**Comment by michaelaye** [comment]
Sorry, this was 3 years ago, can you simply be more specific or quote what was said?

**Comment by michaelaye** [comment]
I don't see any test checking for the presence of pathlib?

**Comment by AndrewAnnex** [comment]
ah... okay I thought this was much more recent. It is in reference to what pandas does from one of your notes. in short never mind

**Comment by rbeyer** [comment]
This is addressed via #38

**Pull request closed without merging**
